FROM python:3.10.8

# set the working directory
WORKDIR /app

# copy the requirements file
COPY requirements.txt /app/requirements.txt

# install the dependencies
RUN pip install --upgrade pip
RUN pip install --upgrade setuptools
RUN pip install nltk
RUN pip install flask
RUN pip install flask_cors
# copy the app files
COPY app.py /app/app.py

# run the app
CMD ["python3", "-m" , "flask", "run", "--host=0.0.0.0"]

#docker build -t my-flask-app .
#docker run -p 5000:5000 my-flask-app